-- OUTPOST ZERO social storage
-- Run once in the Supabase SQL Editor for the project's public schema.
-- Safe to run again: tables are preserved and policies/triggers are refreshed.

create table if not exists public.social_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  handle text not null,
  handle_key text not null,
  display_name text not null default 'operator',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint social_profiles_handle_format check (handle ~ '^[A-Za-z0-9_]{3,32}$'),
  constraint social_profiles_handle_key_format check (handle_key ~ '^[a-z0-9_]{3,32}$')
);

create unique index if not exists social_profiles_handle_key_uidx
  on public.social_profiles(handle_key);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  blocked_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint friendships_distinct_users check (requester_id <> addressee_id),
  constraint friendships_status_check check (status in ('pending','accepted','blocked')),
  constraint friendships_block_owner_check check (
    (status = 'blocked' and blocked_by in (requester_id, addressee_id))
    or (status <> 'blocked' and blocked_by is null)
  )
);

create unique index if not exists friendships_one_pair_uidx
  on public.friendships(least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friendships_requester_recent_idx
  on public.friendships(requester_id, updated_at desc);
create index if not exists friendships_addressee_recent_idx
  on public.friendships(addressee_id, updated_at desc);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint private_messages_distinct_users check (sender_id <> recipient_id),
  constraint private_messages_body_length check (char_length(btrim(body)) between 1 and 500)
);

create index if not exists private_messages_sender_recent_idx
  on public.private_messages(sender_id, created_at desc);
create index if not exists private_messages_recipient_recent_idx
  on public.private_messages(recipient_id, created_at desc);

create or replace function public.social_profiles_normalize()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.handle := btrim(new.handle);
  new.handle_key := lower(new.handle);
  new.display_name := left(coalesce(nullif(btrim(new.display_name), ''), new.handle), 48);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists social_profiles_normalize_trigger on public.social_profiles;
create trigger social_profiles_normalize_trigger
before insert or update on public.social_profiles
for each row execute function public.social_profiles_normalize();

create or replace function public.social_create_profile_for_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  generated_handle text;
  shown_name text;
begin
  shown_name := left(coalesce(
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'name', ''),
    'operator'
  ), 48);
  -- The UUID suffix keeps handles unique without exposing email addresses.
  generated_handle := 'op_' || left(replace(new.id::text, '-', ''), 20);
  insert into public.social_profiles(user_id, handle, handle_key, display_name)
  values(new.id, generated_handle, lower(generated_handle), shown_name)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists social_profile_after_user_insert on auth.users;
create trigger social_profile_after_user_insert
after insert on auth.users
for each row execute function public.social_create_profile_for_user();

insert into public.social_profiles(user_id, handle, handle_key, display_name)
select u.id,
       'op_' || left(replace(u.id::text, '-', ''), 20),
       'op_' || left(replace(u.id::text, '-', ''), 20),
       left(coalesce(
         nullif(u.raw_user_meta_data ->> 'full_name', ''),
         nullif(u.raw_user_meta_data ->> 'name', ''),
         'operator'
       ), 48)
from auth.users u
on conflict (user_id) do nothing;

create or replace function public.friendships_validate_change()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    if new.requester_id <> actor or new.status <> 'pending' or new.blocked_by is not null then
      raise exception 'friend requests must start pending and be created by the requester';
    end if;
    return new;
  end if;

  if new.requester_id <> old.requester_id or new.addressee_id <> old.addressee_id
     or new.created_at <> old.created_at then
    raise exception 'friendship participants are immutable';
  end if;
  if old.status = 'blocked' then
    raise exception 'blocked relationships can only be removed by the blocker';
  elsif new.status = 'accepted' then
    if old.status <> 'pending' or actor <> old.addressee_id then
      raise exception 'only the invited player can accept a pending request';
    end if;
    new.blocked_by := null;
  elsif new.status = 'blocked' then
    if actor not in (old.requester_id, old.addressee_id) then
      raise exception 'only a participant can block this relationship';
    end if;
    new.blocked_by := actor;
  else
    raise exception 'unsupported friendship status change';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists friendships_validate_change_trigger on public.friendships;
create trigger friendships_validate_change_trigger
before insert or update on public.friendships
for each row execute function public.friendships_validate_change();

create or replace function public.private_messages_immutable()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.sender_id <> old.sender_id or new.recipient_id <> old.recipient_id
     or new.body <> old.body or new.created_at <> old.created_at then
    raise exception 'message contents and participants are immutable';
  end if;
  if auth.uid() <> old.recipient_id then
    raise exception 'only the recipient can mark a message read';
  end if;
  return new;
end;
$$;

drop trigger if exists private_messages_immutable_trigger on public.private_messages;
create trigger private_messages_immutable_trigger
before update on public.private_messages
for each row execute function public.private_messages_immutable();

alter table public.social_profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.private_messages enable row level security;

drop policy if exists social_profiles_authenticated_read on public.social_profiles;
create policy social_profiles_authenticated_read on public.social_profiles
for select to authenticated using (true);
drop policy if exists social_profiles_own_insert on public.social_profiles;
create policy social_profiles_own_insert on public.social_profiles
for insert to authenticated with check (user_id = auth.uid());
drop policy if exists social_profiles_own_update on public.social_profiles;
create policy social_profiles_own_update on public.social_profiles
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists friendships_participant_read on public.friendships;
create policy friendships_participant_read on public.friendships
for select to authenticated
using (auth.uid() in (requester_id, addressee_id));
drop policy if exists friendships_requester_insert on public.friendships;
create policy friendships_requester_insert on public.friendships
for insert to authenticated
with check (requester_id = auth.uid() and status = 'pending' and blocked_by is null);
drop policy if exists friendships_participant_update on public.friendships;
create policy friendships_participant_update on public.friendships
for update to authenticated
using (auth.uid() in (requester_id, addressee_id))
with check (auth.uid() in (requester_id, addressee_id));
drop policy if exists friendships_safe_delete on public.friendships;
create policy friendships_safe_delete on public.friendships
for delete to authenticated
using (
  (status = 'pending' and auth.uid() in (requester_id, addressee_id))
  or (status = 'accepted' and auth.uid() in (requester_id, addressee_id))
  or (status = 'blocked' and auth.uid() = blocked_by)
);

drop policy if exists private_messages_participant_read on public.private_messages;
create policy private_messages_participant_read on public.private_messages
for select to authenticated
using (auth.uid() in (sender_id, recipient_id));
drop policy if exists private_messages_friends_insert on public.private_messages;
create policy private_messages_friends_insert on public.private_messages
for insert to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester_id = sender_id and f.addressee_id = recipient_id)
        or (f.requester_id = recipient_id and f.addressee_id = sender_id))
  )
);
drop policy if exists private_messages_recipient_update on public.private_messages;
create policy private_messages_recipient_update on public.private_messages
for update to authenticated
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());
drop policy if exists private_messages_participant_delete on public.private_messages;

revoke all on public.social_profiles, public.friendships, public.private_messages from anon;
revoke all on public.social_profiles, public.friendships, public.private_messages from authenticated;
grant select, insert, update on public.social_profiles to authenticated;
grant select, insert, update, delete on public.friendships to authenticated;
grant select, insert, update on public.private_messages to authenticated;
grant usage, select on sequence public.friendships_id_seq to authenticated;
grant usage, select on sequence public.private_messages_id_seq to authenticated;

-- Realtime is used only as a refresh hint; RLS still controls which rows arrive.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'friendships'
  ) then alter publication supabase_realtime add table public.friendships; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'private_messages'
  ) then alter publication supabase_realtime add table public.private_messages; end if;
end;
$$;
